package com.superum.api.student;

import com.superum.exception.DatabaseException;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Service;

/**
 * <pre>
 * Responsible for handling student commands
 *
 * Uses a pseudo-CQRS model, where commands only mutate the state, but do not return any values, with the exception
 * of cases where a portion of the state is generated by the back end in a non deterministic way which is difficult
 * if not impossible for the front end to read immediately after;
 * Primary example - when the database generates a primary key number value using auto-increment;
 * Counter example - when the database generates a timestamp of create/update (unimportant metadata);
 * </pre>
 */
@Service
public interface ValidStudentCommandService {

    /**
     * <pre>
     * Creates a new student
     *
     * The id field must not be set, but all the other mandatory fields must be set; also, either customerId or
     * startDate field must be set, but not both
     *
     * Before student is created, a random 6 digit code is generated for him
     *
     * partitionId separates different app partitions (please refer to the API file or PartitionController)
     * </pre>
     * @return the created student with id field now set
     *
     * @throws InvalidStudentException if id field was set, a mandatory field was not set, neither customerId or
     * startDate fields were set, or both customerId and startDate were set
     * @throws DatabaseException if database error occurred
     * @throws DataAccessException if an unexpected database error occurred
     */
    ValidStudentDTO create(ValidStudentDTO validStudentDTO, int partitionId);

    /**
     * <pre>
     * Updates an existing student
     *
     * The id field must be set, and at least one more field must be set; also, both customerId and startDate
     * cannot be set
     *
     * partitionId separates different app partitions (please refer to the API file or PartitionController)
     * </pre>
     * @throws InvalidStudentException if id field was not set, no other fields were set or both customerId and
     * startDate were set
     * @throws StudentNotFoundException if a student with specified id does not exist
     * @throws DatabaseException if database error occurred
     * @throws DataAccessException if an unexpected database error occurred
     */
    void update(ValidStudentDTO validStudentDTO, int partitionId);

    /**
     * <pre>
     * Deletes a student with specified id
     *
     * partitionId separates different app partitions (please refer to the API file or PartitionController)
     * </pre>
     * @throws StudentNotFoundException if no student with this id exists
     * @throws UnsafeStudentDeleteException if this student cannot be deleted due to being used in other objects
     * @throws DatabaseException if database error occurred
     * @throws DataAccessException if an unexpected database error occurred
     */
    void delete(int studentId, int partitionId);

}
