package com.superum.helper;

import org.jooq.Condition;
import org.jooq.Record;
import org.jooq.TableField;

import java.util.function.Function;
import java.util.function.Predicate;

/**
 * <pre>
 * Builds a jooq Condition only from certain set fields of a given object
 *
 * Please refer to implementations of API v2 DAO/Queries interfaces for examples
 * </pre>
 * @param <Entity> a class that holds the values to check the fields with
 * @param <TableRecord> jooq Record type for the table that will be checked
 */
public class ConditionBuilder<Entity, TableRecord extends Record> {

    /**
     * <pre>
     * Checks if some field is set, and if it is, adds the check for its value to the Condition
     * </pre>
     * @param hasField a predicate which checks if a field is set, probably a method reference, i.e. Entity::hasId
     * @param tableField a field of the table that should be checked for a value (if this value is present)
     * @param getter a function which retrieves the field's value, probably a method reference, i.e. Entity::getId
     * @param <T> the type of the table field and the object returned by getter
     *
     * @return this builder
     */
    public <T> ConditionBuilder<Entity, TableRecord> fieldCheck(Predicate<Entity> hasField, TableField<TableRecord, T> tableField,  Function<Entity, T> getter) {
        if (hasField.test(customer))
            condition = condition.and(tableField.eq(getter.apply(customer)));
        return this;
    }

    /**
     * @return the Condition generated by this builder
     */
    public Condition finalCondition() {
        return condition;
    }

    // CONSTRUCTORS

    public ConditionBuilder(Entity customer, TableField<TableRecord, Integer> partitionField, int partitionId) {
        this.customer = customer;
        this.condition = partitionField.eq(partitionId);
    }

    // PRIVATE

    private final Entity customer;
    private Condition condition;

}
